basePath: /api
definitions:
  errors.HTTPError:
    properties:
      code:
        type: integer
      message: {}
    type: object
  rest.oAuth2RefreshResult:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  rest.oAuth2SignInUserModel:
    properties:
      password:
        example: password
        maxLength: 64
        minLength: 8
        type: string
      username:
        example: username
        maxLength: 32
        minLength: 4
        type: string
    required:
    - password
    - username
    type: object
  rest.oAuth2SignInUserResult:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  rest.oAuth2SignOutModel:
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        type: string
    required:
    - access_token
    type: object
  rest.oAuth2SignUpUserModel:
    properties:
      password:
        example: password
        maxLength: 64
        minLength: 8
        type: string
      username:
        example: username
        maxLength: 32
        minLength: 4
        type: string
    required:
    - password
    - username
    type: object
host: localhost:8081
info:
  contact: {}
  description: Authentication service
  title: Auth
  version: "1.0"
paths:
  /oauth2/refresh:
    get:
      consumes:
      - application/json
      description: Refresh
      parameters:
      - example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        in: query
        name: t
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.oAuth2RefreshResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.HTTPError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/errors.HTTPError'
      summary: oAuth2 Refresh
      tags:
      - oAuth2
  /oauth2/sign-in:
    post:
      consumes:
      - application/json
      description: Sign in
      parameters:
      - description: Account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/rest.oAuth2SignInUserModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.oAuth2SignInUserResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.HTTPError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/errors.HTTPError'
      summary: oAuth2 Sign In
      tags:
      - oAuth2
  /oauth2/sign-out:
    post:
      consumes:
      - application/json
      description: Sign out
      parameters:
      - description: Access token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/rest.oAuth2SignOutModel'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.HTTPError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/errors.HTTPError'
      summary: oAuth2 Sign Out
      tags:
      - oAuth2
  /oauth2/sign-up:
    post:
      consumes:
      - application/json
      description: Create account
      parameters:
      - description: Account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/rest.oAuth2SignUpUserModel'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.HTTPError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/errors.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.HTTPError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/errors.HTTPError'
      summary: oAuth2 Sign Up
      tags:
      - oAuth2
swagger: "2.0"
