version: '3'

services:
  web:
    build: ./web/
    container_name: 'web'
    ports:
      - '80:80/tcp' # '<EXTERNAL>:<INTERNAL>/tcp'
      - '443:443/tcp'
    restart: always
    depends_on:
      - auth
      - note

  auth:
    build: ./auth/
    container_name: 'auth'
    ports:
      - '8081:8081/tcp'
      - '8091:8091/tcp'
    restart: always
    env_file:
      - ./auth/.env

  note:
    build: ./note/
    container_name: 'note'
    ports:
      - '8092:8092/tcp'
      - '8082:8082/tcp'
    restart: always
    env_file:
      - ./note/.env
