version: '3'

services:
  note:
    container_name: 'note'
    build: .
    ports:
      - '8092:8092/tcp' # '<EXTERNAL>:<INTERNAL>/tcp'
      - '8082:8082/tcp'
    env_file:
      - .env
    restart: always
