version: '3'

services:
  auth:
    container_name: 'auth'
    build: .
    ports:
      - '8081:8081/tcp' # '<EXTERNAL>:<INTERNAL>/tcp'
      - '8091:8091/tcp'
    env_file:
      - .env
    restart: always
