version: '3'

services:
  auth:
    build: .
    container_name: 'unotes-auth'
    ports:
      - '8081:8081/tcp' # '<EXTERNAL>:<INTERNAL>/tcp'
      - '8091:8091/tcp'
    restart: always
    env_file:
      - .env
