version: '3'

services:
  auth-service:
    container_name: 'auth-service'
    build: .
    ports:
      - '8081:8081/tcp' # '<EXTERNAL>:<INTERNAL>/tcp'
    env_file:
      - .env
    restart: always
