// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: getnotes.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetNotesRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetNotesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetNotesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetNotesRequestMultiError, or nil if none found.
func (m *GetNotesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetNotesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetNotesRequestMultiError(errors)
	}

	return nil
}

// GetNotesRequestMultiError is an error wrapping multiple validation errors
// returned by GetNotesRequest.ValidateAll() if the designated constraints
// aren't met.
type GetNotesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetNotesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetNotesRequestMultiError) AllErrors() []error { return m }

// GetNotesRequestValidationError is the validation error returned by
// GetNotesRequest.Validate if the designated constraints aren't met.
type GetNotesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetNotesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetNotesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetNotesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetNotesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetNotesRequestValidationError) ErrorName() string { return "GetNotesRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetNotesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetNotesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetNotesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetNotesRequestValidationError{}

// Validate checks the field values on GetNotesResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetNotesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetNotesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetNotesResponseMultiError, or nil if none found.
func (m *GetNotesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetNotesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Content

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetNotesResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetNotesResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetNotesResponseValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Priority != nil {
		// no validation rules for Priority
	}

	if m.CompletionTime != nil {

		if all {
			switch v := interface{}(m.GetCompletionTime()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetNotesResponseValidationError{
						field:  "CompletionTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetNotesResponseValidationError{
						field:  "CompletionTime",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCompletionTime()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetNotesResponseValidationError{
					field:  "CompletionTime",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetNotesResponseMultiError(errors)
	}

	return nil
}

// GetNotesResponseMultiError is an error wrapping multiple validation errors
// returned by GetNotesResponse.ValidateAll() if the designated constraints
// aren't met.
type GetNotesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetNotesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetNotesResponseMultiError) AllErrors() []error { return m }

// GetNotesResponseValidationError is the validation error returned by
// GetNotesResponse.Validate if the designated constraints aren't met.
type GetNotesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetNotesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetNotesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetNotesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetNotesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetNotesResponseValidationError) ErrorName() string { return "GetNotesResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetNotesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetNotesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetNotesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetNotesResponseValidationError{}
