name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  AUTH_SERVICE_DIGITALOCEAN_REGISTRY: registry.digitalocean.com/unotes
  AUTH_SERVICE_IMAGE_NAME           : unotes-auth-service
  AUTH_SERVICE_CONTAINER_NAME       : unotes-auth-service
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Install "doctl"
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.AUTH_SERVICE_DIGITALOCEAN_ACCESS_TOKEN }}
        
      - name: Building the "auth-service"
        working-directory: auth-service
        run: docker build -t ${{ env.AUTH_SERVICE_DIGITALOCEAN_REGISTRY }}/${{ env.AUTH_SERVICE_IMAGE_NAME }}:$(echo $GITHUB_SHA | head -c7) .
        
      - name: Login to the "DigitalOcean Container Registry"
        run: doctl registry login --expiry-seconds 600
        
      - name: Pushing "auth-service" to the "DigitalOcean Container Registry"
        run: docker push ${{ env.AUTH_SERVICE_DIGITALOCEAN_REGISTRY }}/${{ env.AUTH_SERVICE_IMAGE_NAME }}:$(echo $GITHUB_SHA | head -c7)
        
