name: CI

on:
  push:
    branches: [ "stage" ]
  pull_request:
    branches: [ "stage" ]

env:
  DIGITALOCEAN_REGISTRY: registry.digitalocean.com/unotes
  AUTH_IMAGE_NAME: unotes-auth
  AUTH_REPOSITORY_NAME: unotes

  NOTE_IMAGE_NAME: unotes-note
  NOTE_REPOSITORY_NAME: unotes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install doctl.
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Building auth service.
        working-directory: auth
        run: docker build -t ${{ env.DIGITALOCEAN_REGISTRY }}/${{ env.AUTH_IMAGE_NAME }}:${{ github.sha }} .
      - name: Building note service.
        working-directory: note
        run: docker build -t ${{ env.DIGITALOCEAN_REGISTRY }}/${{ env.NOTE_IMAGE_NAME }}:${{ github.sha }} .

      - name: Login to container registry.
        run: doctl registry login --expiry-seconds 600

      - name: Pushing auth service to the container registry.
        run: docker push ${{ env.DIGITALOCEAN_REGISTRY }}/${{ env.AUTH_REPOSITORY_NAME }}:${{ env.AUTH_IMAGE_NAME }}.${{ github.sha }}
      - name: Pushing note service to the container registry.
        run: docker push ${{ env.DIGITALOCEAN_REGISTRY }}/${{ env.NOTE_REPOSITORY_NAME }}:${{ env.NOTE_IMAGE_NAME }}.${{ github.sha }}
